spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/placeorder/**

    config:
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 5000

server:
  port: 8009

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
